version: '3'
services:
  redis:
    container_name: redis-dev
    image: "redis:alpine"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    labels:
      - "traefik.enable=false"

  web:
    container_name: web
    build: .
    #image: "keko00/web-app:latest-dev"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/trade-web"

    depends_on:
      - redis
